print("Hola mundo desde Python")
print("Esta es una prueba de código en Python")
print("Linea desde DEV")
print("A")
print("B")
print("C")
print("D")
print("E")
print("F")
print("1")
print("2")
print("3")
print("4")
print("5")
print("Uno")
print("Dos")
print("Tres")
print("Cuatro")
print("Cinco")
